---
- name: Install Nextcloud dependencies.
  apt:
    update_cache: true
    name: snapd
    state: present

- name: Add /snap/bin to PATH.
  shell: "source /etc/profile.d/apps-bin-path.sh"
  args:
    executable: /bin/bash
