---
- name: Install Nextcloud dependencies.
  include_tasks: "install-{{ ansible_os_family | default('Debian') | lower }}.yml"

# TK-TODO: Ansible 2.8 apparently will include support for a snap module, so this should be/will be replaced with that once available.
- name: Install Nextcloud from the snap package.
  command: "snap install nextcloud"
  register: snap_install
  changed_when: "'already installed' not in snap_install.stderr_lines[-1]"

# By default, Nextcloud will only trust the localhost domain. Uncomment this to set
# configurations for the domain name(s) of your choosing.
# TODO: Read out `onion-services/<name>/hostname` file for list of
#       domain names that we need to add to `nc_trusted_domains`.
- name: Adjust trusted domains.
  become_flags: "-i"
  command: "nextcloud.occ config:system:set trusted_domains {{ item.key }} --value={{ item.value }}"
  loop: "{{ nc_trusted_domains | dict2items }}"

- name: Install Nextcloud SSL certificate.
  import_tasks: nextcloud-ssl.yml

- name: Create initial admin account and finish installation. (This may take a moment!)
  become: yes
  become_flags: "-i"
  command: "nextcloud.manual-install {{ nc_default_admin_user }} {{ nc_default_admin_password }}"
