---
# Configure the SSL settings. Uncomment only one of the following,
# according to whether you are using a self-signed certificate or you want to
# generate one using Let's Encrypt, which is provided by the Nextcloud snap.
#
# SELF-SIGNED
#
# Note that if you use a self-signed certificate, your browser and those of
# others are likely to throw security warnings.

- name: Create self-signed certificate.
  become_flags: -i
  command: "nextcloud.enable-https self-signed"

# LET'S ENCRYPT
#
# Note that if using Let's Encrypt, you must change the sample e-mail below
# to the one you'd actually like to associate with the cert.
#
# - name: Generate an SSL certificate using Let's Encrypt.
#  expect:
#    command: nextcloud.enable-https lets-encrypt
#    responses:
#      requirements: "y"
#      address: "{{ myfakity@fake.invalid }}"
