# The first thing we will do is set up the Debian 9 server to be able to install Nextcloud.
#
# Install requisite packages.

- name: Install base packages.
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - snapd
    update_cache: yes
