---
- name: Install Nextcloud dependencies.
  apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
    - snapd
    - ufw

- name: Add /snap/bin to $PATH.
  shell: "source /etc/profile.d/apps-bin-path.sh"
  args:
    executable: /bin/bash
