# By default, Nextcloud will only trust localhost. Uncomment this to set
# configurations for the domain name of your choosing.
#
# - name: Adjust trusted domains.
#  become: yes
#  command: sudo -i nextcloud.occ config:system:set trusted_domains {{ trusted_domain_amount }} --value={{ trusted_domain_1 }}
#
# Nextcloud also comes packaged with a UFW firewall. We'll want to tell it to allow
# HTTPS connections.
#
# Allow HTTPS connections via port 443 through the UFW firewall.

- name: Allow port 443 through UFW firewall.
  ufw:
    rule: allow
    port: 443

# Now we'll configure the SSL settings. Uncomment only one of the following,
# according to whether you are using a self-signed certificate or you want to
# generate one using Let's Encrypt, which is provided by the Nextcloud snap.
#
# SELF-SIGNED
#
# Note that if you use a self-signed certificate, your browser and those of
# others are likely to throw security warnings.
#
# - name: Create self-signed certificate.
#  become: yes
#  become_flags: -i
#  command: nextcloud.enable-https self-signed
#
# LET'S ENCRYPT
#
# Note that if using Let's Encrypt, you must change the sample e-mail below
# to the one you'd actually like to associate with the cert.
- name: Generate an SSL certificate using Let's Encrypt.
  expect:
    command: nextcloud.enable-https lets-encrypt
    responses:
      requirements: "y"
      address: "{{ myfakity@fake.invalid }}"
