# NOTE: All variables below are configured in defaults/main.yml EXCEPT for the e-mail
# associated with the SSL certificate if created using Let's Encrypt, which you must
# set in the task below.
#
# First, install and configure the Nextcloud instance.
- name: Download and install the Nextcloud snap package. (This may take a moment!) 
  become: yes
  command: "snap install nextcloud"

# Next, make it so that we can use the /snap environment.
- name: Add /snap/bin to $PATH.
  shell: "sudo -i source /etc/profile.d/apps-bin-path.sh"
  args:
    become: yes
    become_flags: -i

# Create the admin account with which you will administer your Nextcloud instance.
- name: Create admin account. (This may take a moment!)
  become: yes
  command: nextcloud.manual-install {{ nc_default_admin_user }} {{ nc_default_admin_password }}
